name: .ASP CORE_API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Program.cs  # Ajustar con el nombre correcto de la solución
      Wap_Project_Directory: API-CONTROLLERS  # Ajustar con el directorio correcto

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: "Display event data"
      run: |
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

    # Aquí puedes agregar más pasos según lo que necesites para compilar, ejecutar pruebas, empaquetar, etc.
